name: musiku
description: "Your favorite music player!"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

flutter_native_splash:
  color: "#121212"
  image: "./assets/images/splash.png"
  android: true
  ios: true

flutter_launcher_icons:
  android: true
  remove_alpha_ios: true
  ios: true
  image_path: "./assets/icons/musiku.png"
